/**
 * PDF export generator for time tracking data
 */
import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface TimeTrackingPDFData {
  entries: Array<{
    date: string;
    clock_in: string;
    clock_out: string;
    duration_hours: number;
    break_minutes: number;
    overtime_minutes: number;
    group?: string;
  }>;
  summary: {
    total_entries: number;
    total_hours: number;
    total_breaks_minutes: number;
    total_overtime_minutes: number;
    average_hours_per_day: number;
  };
  user: {
    name: string;
    email: string;
    period: string;
  };
}

interface HabitsPDFData {
  entries: Array<{
    date: string;
    habit_name: string;
    category: string;
    type: string;
    completed_at?: string;
    duration_minutes?: number;
    count_value?: number;
    mood_rating?: number;
    notes?: string;
  }>;
  summary: {
    total_entries: number;
    unique_habits: number;
    completed_days: number;
    average_entries_per_day: number;
  };
  user: {
    name: string;
    email: string;
    period: string;
  };
}

export function generateTimeTrackingPDF(exportData: TimeTrackingPDFData): Buffer {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text('Time Tracking Report', 20, 20);

  // User info
  doc.setFontSize(12);
  doc.text(`User: ${exportData.user.name} (${exportData.user.email})`, 20, 35);
  doc.text(`Period: ${exportData.user.period}`, 20, 45);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 55);

  // Summary section
  doc.setFontSize(16);
  doc.text('Summary', 20, 75);

  const summaryData = [
    ['Total Entries', exportData.summary.total_entries.toString()],
    ['Total Hours', exportData.summary.total_hours.toFixed(2)],
    ['Total Break Time', `${exportData.summary.total_breaks_minutes} minutes`],
    ['Total Overtime', `${exportData.summary.total_overtime_minutes} minutes`],
    ['Average Hours/Day', exportData.summary.average_hours_per_day.toFixed(2)]
  ];

  doc.autoTable({
    startY: 85,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold' }
    }
  });

  // Time entries table
  doc.setFontSize(16);
  doc.text('Time Entries', 20, doc.lastAutoTable.finalY + 20);

  const tableData = exportData.entries.map(entry => [
    entry.date,
    entry.clock_in,
    entry.clock_out,
    entry.duration_hours.toFixed(2) + 'h',
    entry.break_minutes + 'm',
    entry.overtime_minutes + 'm',
    entry.group || 'Personal'
  ]);

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 30,
    head: [['Date', 'Clock In', 'Clock Out', 'Duration', 'Breaks', 'Overtime', 'Group']],
    body: tableData,
    theme: 'striped',
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    headStyles: {
      fillColor: [59, 130, 246], // Blue color
      textColor: 255
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 22 },
      2: { cellWidth: 22 },
      3: { cellWidth: 20 },
      4: { cellWidth: 18 },
      5: { cellWidth: 20 },
      6: { cellWidth: 25 }
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Generated by TimeTracker - Page ${i} of ${pageCount}`,
      20,
      doc.internal.pageSize.height - 10
    );
  }

  return Buffer.from(doc.output('arraybuffer'));
}

export function generateHabitsPDF(exportData: HabitsPDFData): Buffer {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text('Habits Tracking Report', 20, 20);

  // User info
  doc.setFontSize(12);
  doc.text(`User: ${exportData.user.name} (${exportData.user.email})`, 20, 35);
  doc.text(`Period: ${exportData.user.period}`, 20, 45);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 55);

  // Summary section
  doc.setFontSize(16);
  doc.text('Summary', 20, 75);

  const summaryData = [
    ['Total Entries', exportData.summary.total_entries.toString()],
    ['Unique Habits', exportData.summary.unique_habits.toString()],
    ['Completed Days', exportData.summary.completed_days.toString()],
    ['Avg Entries/Day', exportData.summary.average_entries_per_day.toFixed(1)]
  ];

  doc.autoTable({
    startY: 85,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold' }
    }
  });

  // Habits entries table
  doc.setFontSize(16);
  doc.text('Habit Entries', 20, doc.lastAutoTable.finalY + 20);

  const tableData = exportData.entries.map(entry => [
    entry.date,
    entry.habit_name,
    entry.category,
    entry.type,
    entry.completed_at || '-',
    entry.duration_minutes?.toString() || '-',
    entry.count_value?.toString() || '-',
    entry.mood_rating?.toString() || '-'
  ]);

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 30,
    head: [['Date', 'Habit', 'Category', 'Type', 'Completed', 'Duration', 'Count', 'Mood']],
    body: tableData,
    theme: 'striped',
    styles: {
      fontSize: 8,
      cellPadding: 2
    },
    headStyles: {
      fillColor: [34, 197, 94], // Green color
      textColor: 255
    },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 30 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 18 },
      6: { cellWidth: 15 },
      7: { cellWidth: 15 }
    }
  });

  // Add notes section if any entries have notes
  const entriesWithNotes = exportData.entries.filter(entry => entry.notes);
  if (entriesWithNotes.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.text('Notes', 20, 20);

    let yPosition = 35;
    entriesWithNotes.forEach(entry => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFontSize(12);
      doc.text(`${entry.date} - ${entry.habit_name}:`, 20, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      const splitNotes = doc.splitTextToSize(entry.notes || '', 170);
      doc.text(splitNotes, 20, yPosition);
      yPosition += splitNotes.length * 5 + 10;
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Generated by TimeTracker - Page ${i} of ${pageCount}`,
      20,
      doc.internal.pageSize.height - 10
    );
  }

  return Buffer.from(doc.output('arraybuffer'));
}

export function generateCombinedPDF(timeData: TimeTrackingPDFData, habitsData: HabitsPDFData): Buffer {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(24);
  doc.text('Combined Activity Report', 20, 20);

  // User info
  doc.setFontSize(12);
  doc.text(`User: ${timeData.user.name} (${timeData.user.email})`, 20, 35);
  doc.text(`Period: ${timeData.user.period}`, 20, 45);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 55);

  // Combined summary
  doc.setFontSize(16);
  doc.text('Activity Overview', 20, 75);

  const summaryData = [
    ['Work Hours Tracked', timeData.summary.total_hours.toFixed(2)],
    ['Work Sessions', timeData.summary.total_entries.toString()],
    ['Habits Tracked', habitsData.summary.total_entries.toString()],
    ['Unique Habits', habitsData.summary.unique_habits.toString()],
    ['Avg Work Hours/Day', timeData.summary.average_hours_per_day.toFixed(2)],
    ['Avg Habits/Day', habitsData.summary.average_entries_per_day.toFixed(1)]
  ];

  doc.autoTable({
    startY: 85,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold' }
    }
  });

  // Add time tracking section
  doc.addPage();
  doc.setFontSize(18);
  doc.text('Work Time Tracking', 20, 20);

  const timeTableData = timeData.entries.slice(0, 20).map(entry => [
    entry.date,
    entry.clock_in,
    entry.clock_out,
    entry.duration_hours.toFixed(2) + 'h',
    entry.overtime_minutes + 'm'
  ]);

  doc.autoTable({
    startY: 35,
    head: [['Date', 'Clock In', 'Clock Out', 'Duration', 'Overtime']],
    body: timeTableData,
    theme: 'striped',
    styles: { fontSize: 10 }
  });

  // Add habits section
  doc.addPage();
  doc.setFontSize(18);
  doc.text('Habits Tracking', 20, 20);

  const habitsTableData = habitsData.entries.slice(0, 20).map(entry => [
    entry.date,
    entry.habit_name,
    entry.category,
    entry.completed_at || '-',
    entry.mood_rating?.toString() || '-'
  ]);

  doc.autoTable({
    startY: 35,
    head: [['Date', 'Habit', 'Category', 'Completed', 'Mood']],
    body: habitsTableData,
    theme: 'striped',
    styles: { fontSize: 10 }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Generated by TimeTracker - Page ${i} of ${pageCount}`,
      20,
      doc.internal.pageSize.height - 10
    );
  }

  return Buffer.from(doc.output('arraybuffer'));
}